### ISSUE TITLE
CO2.0: Maker details not correctly linked / displayed

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1545]
On [live](https://collection.sciencemuseumgroup.org.uk/objects/co413782/) we have this:
<img width="599" alt="Screenshot 2024-02-05 at 17 17 33" src="https://github.com/TheScienceMuseum/collectionsonline/assets/91365/08694643-dedc-409e-9f79-f2bde2400120">

On [staging](http://localhost:8000/objects/co413782/railway-bridge-section-bridge-section) we have this, where Stephenson is listed twice and not like the second time. The second version is also in a different format ie. 'Stephenson, Robert`. 

![Image](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/2b5dd824-0d09-4996-bc4f-bfb32c54a116)

**Tasks**
- [ ] Decide what to do about `"https://github.com/entity": "literal"` roles?
- [ ] Convert MAKER to correct format (as per other values, ie. transpose  'Stephenson, Robert`)
- [ ] Link MAKER to correct record (as per other values, ie. transpose  'Stephenson, Robert`.)
- [ ] If the same person is listed twice as MAKER and ENGINEER then **only** display the more specific role.

It is probably worth us spot-checking a few more people/companies to ensure they are displaying their details correctly and some new index quirk hasn't change the way we are displaying them.

ie. this record on live vs dev
https://collection.sciencemuseumgroup.org.uk/objects/co229888/the-queen-of-scots-pullman-poster

**Comment by jamieu** [comment]
"creation": [
          {
            "date": [
              {
                "earliest": 1926,
                "latest": 1926,
                "primary": true,
                "value": "circa 1926"
              }
            ],
            "maker": [
              {
                "@link": {
                  "role": [
                    {
                      "value": "artist"
                    }
                  ],
                  "type": "reference"
                },
                "admin": {
                  "id": "agent-29106",
                  "uid": "cp29106",
                  "uuid": "062f46f2-b033-3e93-8e23-11094517d239"
                },
                "summary_title": "Septimus Edwin Scott"
              },
              {
                "@link": {
                  "role": [
                    {
                      "value": "publisher"
                    }
                  ],
                  "type": "reference"
                },
                "admin": {
                  "id": "agent-7555",
                  "uid": "cp7555",
                  "uuid": "e252b77e-273f-3daf-a1d0-38a230167b60"
                },
                "summary_title": "Pullman Car Company"
              },
              {
                "@link": {
                  "role": [
                    {
                      "value": "maker"
                    }
                  ],
                  "type": "reference"
                },
                "admin": {
                  "id": "agent-109656",
                  "uid": "cp109656",
                  "uuid": "c5dfb112-3904-3db4-8c25-7df09ea2d8a2"
                },
                "summary_title": "David Allen and Sons Limited"
              }
            ]
          }
        ]
      },

**Comment by jamieu** [comment]
Resolved, but may want to revert / revisit if we notice missing makers post launch
https://github.com/TheScienceMuseum/collectionsonline/pull/1616
