### ISSUE TITLE
Priority roadmap | Upcoming sprints

### ISSUE THREAD

**Issue by iteles** [TheScienceMuseum/collectionsonline#206]
@SimonLab @Danwhy I intend to fill this out with some more detail and linking to existing issues, but wanted to make sure I got this up before I was internet-less until Saturday! If you already know of issues you have opened against some of these, please link them here.

As discussed with @jamieu today, priorities for the upcoming sprints are as finished

+ [ ] Filters and faceting finish - recheck with new index
+ [x] List view 
+ [x] Details section of page #159 
+ [ ] Ensure documentation is up to date (ongoing but this is an additional checkpoint)
+ First pass at:
  + [ ] Autocomplete on people, categories, object
  + [ ] Default ordering
  + [ ] Ranking for different fields (weightings for particular values on particular fields)
  + [ ] Ranking for word proximity, i.e. If two words are next to each other, they pretty much always have to be right next to each other
+ [x] Implement list view #204 :arrow_left: Not sure about the priority of this one as we only discussed it in passing at the end!
+ [ ] Finalising related objects #205
+ [x] Twitter (not high priority so this will be moved to after images if we have these earlier)
+ [ ] First pass at deep zoom

+ [ ] Images - dependency on when we have these
